### PR TITLE
Change to Ubuntu Linux, fix splashscreen

### LINKED ISSUE #430: text in splash screen broken
Something is missing on the official buildserver: The text in the splash screen is only shown as squares, like □□□□□□□ □□□.

### PR DESCRIPTION
**Pull request by mgmax**
Now the splash screen version text works again. Somehow, this feels like a "how many engineer hours does it take to fix a broken lightbulb?" joke, just with splashcreen instead of lightbulb :-D

Ubuntu has all the dependencies we need*, so I switched to that. Version 18.04 will be (more or less) supported for the next five years.

*except for `makepkg`, and making that work outside of Arch Linux was quite tedious since I couldn't find a complete list of build dependencies...

Fixes https://github.com/t-oster/VisiCut/issues/430

### CODE REVIEW

**Comment by t-oster** [comment]
Nice, but did you forget to commit the dockerfile?

**Comment by mgmax** [comment]
sorry, should be fixed now

**Comment by t-oster** [comment]
Tanks for your work. I am busy today maybe in the evening I will update my servers.
However since any RUN command in the dockerfile creates a new layer we should combine most of the commands so we get a less scattered Result. I will do this as soon as i get on my PC

**Comment by t-oster** [comment]
Sorry again, but is the fake-arch-package file missing also?

**Comment by mgmax** [comment]
fixed now, sorry...

**Pull request merged**
